### ISSUE TITLE
mutiatlas labels

### ISSUE THREAD

**Issue by johndlewis** [CobraLab/antsRegistration-MAGeT#73] opened 2017-02-09 18:53 UTC
I think there's a bug when providing multiple atlases.  The info from mb.sh -- check shows the correct number of atlases, but one label file.  I believe that the fix is:

# labels=$(ls $(echo ${atlases} | cut -d " " -f 1 | sed -r 's/_(t1|T1w|t2|T2w)./_label\/g') | sed 's/input.*label/label/g' || true)
labels=$(ls input/atlas/_$(ls $(echo ${atlases} | cut -d " " -f 1 | sed -r 's/_(t1|T1w|t2|T2w)./_label\*/g') | sed 's/input.*label/label/g' || true))

**Comment by gdevenyi** [comment] 2017-02-09 18:55
Can you please provide a link to the exact code line.

**Comment by gdevenyi** [comment] 2017-02-09 19:24
As you can see from the comment directly above, this code is correct as intended:
https://github.com/CobraLab/antsRegistration-MAGeT/blob/master/bin/mb.sh#L115-L116

You are mis-interpreting the status output as being the total number of labels. I am counting and using the labels defined for the first atlas, as it is required that each atlas have the same number of label files.

I will push a clarification to the status line.

Closing, NOTABUG

**Comment by gdevenyi** [comment] 2017-02-09 19:25
Fixed by 1988612dabcd72ed873cebc95039f7047e8ede29

**Closed by gdevenyi** 2017-02-09 19:24 UTC
